# Cilium on K3s / AlmaLinux
# kube-proxy replacement + Gateway API

ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
      - "10.42.0.0/16"

k8sServiceHost: "192.168.2.201"
k8sServicePort: 6443

kubeProxyReplacement: true

socketLB:
  enabled: true
  hostNamespaceOnly: true

gatewayAPI:
  enabled: true
  enableAlpn: true
  enableAppProtocol: true

operator:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  prometheus:
    enabled: true
    port: 9963
    serviceMonitor:
      enabled: false
      labels:
        release: monitoring
      interval: 30s

  dashboards:
    enabled: true
    label: grafana_dashboard
    labelValue: "1"
    annotations: {}

resources:
  requests:
    cpu: 150m
    memory: 512Mi

prometheus:
  enabled: true
  port: 9962
  serviceMonitor:
    enabled: false
    labels:
      release: monitoring
    interval: 30s

envoy:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  prometheus:
    enabled: true
    port: "9964"
    serviceMonitor:
      enabled: false
      labels:
        release: monitoring
      interval: 30s

hubble:
  enabled: true

  relay:
    enabled: true

  ui:
    enabled: true
